### ISSUE TITLE
Refactor podcast RSS fetching

### ISSUE THREAD

**Issue by OKinane** [pentium-fm/pentium.live#4]
Hi,

The RSS fetching/parsing logic is duplicated in 3 different files.

It should be implemented only once.

**Comment by JefferyHus** [comment]
True, because we are refactoring the whole project we left few components using local states there till we are sure we no more need it. Thanks for contributing : )

**Comment by JefferyHus** [comment]
[#fc96d7c](https://github.com/pentium-fm/pentium.live/commit/916afb56473155b33b04f5a65e871b90e6b53c44) This commit fixes this issue.

**Comment by OKinane** [comment]
There's still duplicated fetching/parsing logic in two files:
https://github.com/pentium-fm/pentium.live/blob/master/src/actions/index.js#L5-L23
https://github.com/pentium-fm/pentium.live/blob/master/src/store/api/index.js#L14-L32

**Comment by JefferyHus** [comment]
You are referring to an old commit mate.

**Comment by OKinane** [comment]
My links point to master branch's head, I don't see how they can be old.

**Comment by JefferyHus** [comment]
Yes you were right, my bad. Didn't notice the actions folder and mistook it with the existing and new one under `store`

**Comment by JefferyHus** [comment]
It's fixed now. Thanks.
